-- SCIENCE CORE V1
-- Applied to Supabase project oxjjmozpjbnawewdyuso on 2026-10-01.
-- Preregistration, immutable snapshots, reproducible runs and anti-leakage guards.

alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;

create table public.experiments (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  hypothesis text not null,
  null_hypothesis text not null,
  primary_metric text not null,
  secondary_metrics text[] not null default '{}',
  planned_start_draw integer not null check (planned_start_draw > 0),
  planned_min_draws integer not null check (planned_min_draws > 0),
  planned_end_draw integer check (planned_end_draw is null or planned_end_draw >= planned_start_draw),
  protocol_version text not null default 'SCIENCE_CORE_V1',
  pre_registration jsonb not null default '{}'::jsonb check (jsonb_typeof(pre_registration) = 'object'),
  status text not null default 'DRAFT' check (status in ('DRAFT','FROZEN','RUNNING','COMPLETED','ABORTED')),
  notes text,
  created_at timestamptz not null default now(),
  frozen_at timestamptz,
  completed_at timestamptz
);

alter table public.model_versions
  add column model_family text not null default 'PREDICTIVE'
    check (model_family in ('PREDICTIVE','BASELINE','CONTROL','NULL_MODEL'));

create table public.experiment_models (
  experiment_id uuid not null references public.experiments(id) on delete cascade,
  model_version_id uuid not null references public.model_versions(id) on delete restrict,
  role text not null check (role in ('CHAMPION','CHALLENGER','CONTROL')),
  label text not null,
  config jsonb not null default '{}'::jsonb check (jsonb_typeof(config) = 'object'),
  created_at timestamptz not null default now(),
  primary key (experiment_id, model_version_id)
);
create index experiment_models_model_version_id_idx on public.experiment_models(model_version_id);

create table public.experiment_events (
  id bigint generated by default as identity primary key,
  experiment_id uuid not null references public.experiments(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  created_at timestamptz not null default now()
);
create index experiment_events_experiment_id_idx on public.experiment_events(experiment_id);

create table public.dataset_snapshots (
  id uuid primary key default gen_random_uuid(),
  label text not null,
  through_draw_number integer not null check (through_draw_number > 0),
  draw_count integer not null default 0 check (draw_count >= 0),
  dataset_sha256 text unique check (dataset_sha256 is null or dataset_sha256 ~ '^[0-9a-f]{64}$'),
  manifest jsonb not null default '{}'::jsonb check (jsonb_typeof(manifest) = 'object'),
  created_at timestamptz not null default now(),
  frozen_at timestamptz
);

create table public.dataset_snapshot_draws (
  snapshot_id uuid not null references public.dataset_snapshots(id) on delete cascade,
  draw_number integer not null check (draw_number > 0),
  draw_date date not null,
  validation_status text not null check (validation_status in ('OFICIAL','SECUNDARIO_VERIFICADO','SECUNDARIO_NO_VERIFICADO','RECONSTRUIDO','CONFLICTO')),
  numbers smallint[] not null check (cardinality(numbers) = 10),
  row_sha256 text not null check (row_sha256 ~ '^[0-9a-f]{64}$'),
  primary key (snapshot_id, draw_number)
);

create table public.feature_snapshots (
  id uuid primary key default gen_random_uuid(),
  target_draw_number integer not null check (target_draw_number > 0),
  trained_through_draw_number integer not null check (trained_through_draw_number > 0),
  dataset_snapshot_id uuid not null references public.dataset_snapshots(id) on delete restrict,
  feature_version text not null,
  feature_config jsonb not null default '{}'::jsonb check (jsonb_typeof(feature_config) = 'object'),
  git_commit_sha text not null check (git_commit_sha ~ '^[0-9a-f]{40}([0-9a-f]{24})?$'),
  snapshot_sha256 text unique check (snapshot_sha256 is null or snapshot_sha256 ~ '^[0-9a-f]{64}$'),
  created_at timestamptz not null default now(),
  frozen_at timestamptz,
  check (trained_through_draw_number < target_draw_number),
  unique (target_draw_number, feature_version, dataset_snapshot_id)
);
create index feature_snapshots_dataset_snapshot_id_idx on public.feature_snapshots(dataset_snapshot_id);

create table public.feature_snapshot_values (
  snapshot_id uuid not null references public.feature_snapshots(id) on delete cascade,
  number smallint not null check (number between 0 and 99),
  features jsonb not null check (jsonb_typeof(features) = 'object'),
  row_sha256 text not null check (row_sha256 ~ '^[0-9a-f]{64}$'),
  primary key (snapshot_id, number)
);

alter table public.model_runs alter column run_hash drop not null;
alter table public.model_runs
  add column experiment_id uuid not null references public.experiments(id) on delete restrict,
  add column dataset_snapshot_id uuid not null references public.dataset_snapshots(id) on delete restrict,
  add column feature_snapshot_id uuid not null references public.feature_snapshots(id) on delete restrict,
  add column run_kind text not null default 'MODEL' check (run_kind in ('MODEL','RANDOM_CONTROL','COLD_CONTROL','NULL_CONTROL')),
  add column protocol_version text not null default 'SCIENCE_CORE_V1',
  add column git_commit_sha text not null check (git_commit_sha ~ '^[0-9a-f]{40}([0-9a-f]{24})?$'),
  add column dataset_sha256 text check (dataset_sha256 is null or dataset_sha256 ~ '^[0-9a-f]{64}$'),
  add column features_sha256 text check (features_sha256 is null or features_sha256 ~ '^[0-9a-f]{64}$'),
  add column random_seed bigint not null;
create index model_runs_experiment_id_idx on public.model_runs(experiment_id);
create index model_runs_dataset_snapshot_id_idx on public.model_runs(dataset_snapshot_id);
create index model_runs_feature_snapshot_id_idx on public.model_runs(feature_snapshot_id);

alter table public.portfolios alter column run_id set not null;
alter table public.portfolios
  add column protocol_version text not null default 'SCIENCE_CORE_V1',
  add column optimizer_seed bigint not null default 0,
  add column portfolio_sha256 text unique check (portfolio_sha256 is null or portfolio_sha256 ~ '^[0-9a-f]{64}$');

create or replace function internal.sha256_hex(p_text text)
returns text language sql immutable security invoker set search_path = '' as $$
  select pg_catalog.encode(extensions.digest(pg_catalog.convert_to(p_text, 'UTF8'), 'sha256'), 'hex');
$$;
revoke execute on function internal.sha256_hex(text) from public, anon, authenticated;
grant execute on function internal.sha256_hex(text) to service_role;

create or replace function internal.prepare_dataset_snapshot_draw()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare distinct_count integer; in_range boolean;
begin
  select count(distinct x), bool_and(x between 0 and 99) into distinct_count, in_range
  from pg_catalog.unnest(new.numbers) as x;
  if pg_catalog.cardinality(new.numbers) <> 10 or distinct_count <> 10 or not coalesce(in_range, false) then
    raise exception 'dataset snapshot draw % must contain exactly 10 unique numbers in 0..99', new.draw_number;
  end if;
  new.row_sha256 := internal.sha256_hex(new.draw_number::text || '|' || new.draw_date::text || '|' || new.validation_status || '|' || pg_catalog.array_to_string(new.numbers, ','));
  return new;
end;
$$;

create or replace function internal.guard_dataset_snapshot_draw_change()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare sid uuid; frozen timestamptz;
begin
  sid := case when tg_op = 'DELETE' then old.snapshot_id else new.snapshot_id end;
  select s.frozen_at into frozen from public.dataset_snapshots s where s.id = sid;
  if frozen is not null then raise exception 'dataset snapshot % is frozen and immutable', sid; end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
create trigger dataset_snapshot_draw_guard before insert or update or delete on public.dataset_snapshot_draws for each row execute function internal.guard_dataset_snapshot_draw_change();
create trigger dataset_snapshot_draw_prepare before insert or update on public.dataset_snapshot_draws for each row execute function internal.prepare_dataset_snapshot_draw();

create or replace function internal.guard_dataset_snapshot_header()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare n integer; max_draw integer; rows_blob text;
begin
  if tg_op = 'DELETE' then
    if old.frozen_at is not null then raise exception 'frozen dataset snapshot % cannot be deleted', old.id; end if;
    return old;
  end if;
  if old.frozen_at is not null then raise exception 'frozen dataset snapshot % cannot be modified', old.id; end if;
  if old.frozen_at is null and new.frozen_at is not null then
    select count(*), max(d.draw_number), string_agg(d.row_sha256, '' order by d.draw_number) into n, max_draw, rows_blob
    from public.dataset_snapshot_draws d where d.snapshot_id = new.id;
    if n = 0 or max_draw <> new.through_draw_number then
      raise exception 'dataset snapshot % cannot freeze: rows %, max draw %, expected through %', new.id, n, max_draw, new.through_draw_number;
    end if;
    new.draw_count := n;
    new.dataset_sha256 := internal.sha256_hex(new.through_draw_number::text || '|' || new.manifest::text || '|' || coalesce(rows_blob, ''));
  end if;
  return new;
end;
$$;
create trigger dataset_snapshot_header_guard before update or delete on public.dataset_snapshots for each row execute function internal.guard_dataset_snapshot_header();

create or replace function internal.prepare_feature_snapshot_value()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  new.row_sha256 := internal.sha256_hex(new.number::text || '|' || new.features::text);
  return new;
end;
$$;

create or replace function internal.guard_feature_snapshot_value_change()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare sid uuid; frozen timestamptz;
begin
  sid := case when tg_op = 'DELETE' then old.snapshot_id else new.snapshot_id end;
  select s.frozen_at into frozen from public.feature_snapshots s where s.id = sid;
  if frozen is not null then raise exception 'feature snapshot % is frozen and immutable', sid; end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
create trigger feature_snapshot_value_guard before insert or update or delete on public.feature_snapshot_values for each row execute function internal.guard_feature_snapshot_value_change();
create trigger feature_snapshot_value_prepare before insert or update on public.feature_snapshot_values for each row execute function internal.prepare_feature_snapshot_value();

create or replace function internal.guard_feature_snapshot_header()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare n integer; min_num integer; max_num integer; rows_blob text; ds_through integer; ds_frozen timestamptz;
begin
  if tg_op = 'DELETE' then
    if old.frozen_at is not null then raise exception 'frozen feature snapshot % cannot be deleted', old.id; end if;
    return old;
  end if;
  if old.frozen_at is not null then raise exception 'frozen feature snapshot % cannot be modified', old.id; end if;
  if old.frozen_at is null and new.frozen_at is not null then
    select d.through_draw_number, d.frozen_at into ds_through, ds_frozen from public.dataset_snapshots d where d.id = new.dataset_snapshot_id;
    if ds_frozen is null or ds_through <> new.trained_through_draw_number then
      raise exception 'feature snapshot % dataset must be frozen exactly through trained draw %', new.id, new.trained_through_draw_number;
    end if;
    select count(*), min(v.number), max(v.number), string_agg(v.row_sha256, '' order by v.number) into n, min_num, max_num, rows_blob
    from public.feature_snapshot_values v where v.snapshot_id = new.id;
    if n <> 100 or min_num <> 0 or max_num <> 99 then
      raise exception 'feature snapshot % requires exactly numbers 00..99; got count %, min %, max %', new.id, n, min_num, max_num;
    end if;
    new.snapshot_sha256 := internal.sha256_hex(new.target_draw_number::text || '|' || new.trained_through_draw_number::text || '|' || new.dataset_snapshot_id::text || '|' || new.feature_version || '|' || new.feature_config::text || '|' || new.git_commit_sha || '|' || coalesce(rows_blob, ''));
  end if;
  return new;
end;
$$;
create trigger feature_snapshot_header_guard before update or delete on public.feature_snapshots for each row execute function internal.guard_feature_snapshot_header();

create or replace function internal.guard_model_version_frozen()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if tg_op = 'DELETE' then
    if old.frozen_at is not null then raise exception 'frozen model version % cannot be deleted', old.id; end if;
    return old;
  end if;
  if old.frozen_at is not null then raise exception 'frozen model version % cannot be modified', old.id; end if;
  return new;
end;
$$;
create trigger model_version_frozen_guard before update or delete on public.model_versions for each row execute function internal.guard_model_version_frozen();

create or replace function internal.guard_experiment_models_change()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare eid uuid; frozen timestamptz;
begin
  eid := case when tg_op = 'DELETE' then old.experiment_id else new.experiment_id end;
  select e.frozen_at into frozen from public.experiments e where e.id = eid;
  if frozen is not null then raise exception 'experiment % is frozen; model roster is immutable', eid; end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
create trigger experiment_models_guard before insert or update or delete on public.experiment_models for each row execute function internal.guard_experiment_models_change();

create or replace function internal.guard_experiment()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare control_count integer; candidate_count integer; unfrozen_models integer;
begin
  if tg_op = 'DELETE' then
    if old.frozen_at is not null then raise exception 'frozen experiment % cannot be deleted', old.id; end if;
    return old;
  end if;
  if old.frozen_at is not null then
    if (to_jsonb(new) - array['status','completed_at']) <> (to_jsonb(old) - array['status','completed_at']) then
      raise exception 'experiment % preregistration is frozen; only lifecycle status may change', old.id;
    end if;
    if old.status = 'FROZEN' and new.status not in ('FROZEN','RUNNING','ABORTED') then raise exception 'invalid experiment transition % -> %', old.status, new.status;
    elsif old.status = 'RUNNING' and new.status not in ('RUNNING','COMPLETED','ABORTED') then raise exception 'invalid experiment transition % -> %', old.status, new.status;
    elsif old.status in ('COMPLETED','ABORTED') and new.status <> old.status then raise exception 'terminal experiment status % cannot transition', old.status;
    end if;
    if new.status = 'COMPLETED' and new.completed_at is null then raise exception 'completed experiment requires completed_at'; end if;
    return new;
  end if;
  if old.frozen_at is null and new.frozen_at is not null then
    if new.status <> 'FROZEN' then raise exception 'experiment must enter FROZEN status when preregistration is frozen'; end if;
    if new.pre_registration = '{}'::jsonb then raise exception 'experiment preregistration cannot be empty'; end if;
    select count(*) filter (where em.role = 'CONTROL'), count(*) filter (where em.role in ('CHAMPION','CHALLENGER')), count(*) filter (where mv.frozen_at is null)
      into control_count, candidate_count, unfrozen_models
    from public.experiment_models em join public.model_versions mv on mv.id = em.model_version_id
    where em.experiment_id = new.id;
    if control_count < 1 or candidate_count < 1 then raise exception 'experiment % requires at least one candidate and one control model', new.id; end if;
    if unfrozen_models > 0 then raise exception 'all experiment model versions must be frozen before preregistration freeze'; end if;
  end if;
  return new;
end;
$$;
create trigger experiment_guard before update or delete on public.experiments for each row execute function internal.guard_experiment();

create or replace function internal.log_experiment_transition()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  if old.frozen_at is null and new.frozen_at is not null then
    insert into public.experiment_events(experiment_id, event_type, payload) values (new.id, 'FROZEN', jsonb_build_object('status', new.status, 'frozen_at', new.frozen_at));
  elsif old.status is distinct from new.status then
    insert into public.experiment_events(experiment_id, event_type, payload) values (new.id, 'STATUS_CHANGED', jsonb_build_object('from', old.status, 'to', new.status, 'completed_at', new.completed_at));
  end if;
  return new;
end;
$$;
create trigger experiment_transition_log after update on public.experiments for each row execute function internal.log_experiment_transition();

create or replace function internal.prevent_event_mutation()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin raise exception 'experiment events are append-only'; end;
$$;
create trigger experiment_events_append_only before update or delete on public.experiment_events for each row execute function internal.prevent_event_mutation();

create or replace function internal.guard_model_prediction_change()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare rid uuid; frozen timestamptz;
begin
  rid := case when tg_op = 'DELETE' then old.run_id else new.run_id end;
  select r.frozen_at into frozen from public.model_runs r where r.id = rid;
  if frozen is not null then raise exception 'model run % is frozen; predictions are immutable', rid; end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
create trigger model_prediction_guard before insert or update or delete on public.model_predictions for each row execute function internal.guard_model_prediction_change();

create or replace function internal.guard_model_run()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare
  exp_frozen timestamptz; model_frozen timestamptz; fs_frozen timestamptz; fs_target integer; fs_trained integer; fs_dataset uuid; fs_hash text;
  ds_frozen timestamptz; ds_through integer; ds_hash text; prediction_count integer; probability_count integer; probability_sum double precision; pred_blob text;
begin
  if tg_op = 'DELETE' then
    if old.frozen_at is not null then raise exception 'frozen model run % cannot be deleted', old.id; end if;
    return old;
  end if;
  if old.frozen_at is not null then raise exception 'frozen model run % cannot be modified', old.id; end if;
  if old.frozen_at is null and new.frozen_at is not null then
    select e.frozen_at into exp_frozen from public.experiments e where e.id = new.experiment_id;
    select m.frozen_at into model_frozen from public.model_versions m where m.id = new.model_version_id;
    select f.frozen_at, f.target_draw_number, f.trained_through_draw_number, f.dataset_snapshot_id, f.snapshot_sha256 into fs_frozen, fs_target, fs_trained, fs_dataset, fs_hash from public.feature_snapshots f where f.id = new.feature_snapshot_id;
    select d.frozen_at, d.through_draw_number, d.dataset_sha256 into ds_frozen, ds_through, ds_hash from public.dataset_snapshots d where d.id = new.dataset_snapshot_id;
    if exp_frozen is null then raise exception 'model run requires a frozen experiment'; end if;
    if model_frozen is null then raise exception 'model run requires a frozen model version'; end if;
    if fs_frozen is null or ds_frozen is null then raise exception 'model run requires frozen feature and dataset snapshots'; end if;
    if fs_target <> new.target_draw_number or fs_trained <> new.trained_through_draw_number then raise exception 'feature snapshot cutoff/target does not match model run'; end if;
    if fs_dataset <> new.dataset_snapshot_id or ds_through <> new.trained_through_draw_number then raise exception 'dataset snapshot lineage does not match model run'; end if;
    select count(*), count(p.probability), sum(p.probability), string_agg(p.number::text || ':' || p.rank::text || ':' || p.probability::text || ':' || coalesce(p.score::text,''), '|' order by p.number)
      into prediction_count, probability_count, probability_sum, pred_blob
    from public.model_predictions p where p.run_id = new.id;
    if new.protocol_version = 'SCIENCE_CORE_V1' then
      if prediction_count <> 100 or probability_count <> 100 then raise exception 'SCIENCE_CORE_V1 run requires 100 ranked probabilities; got predictions %, probabilities %', prediction_count, probability_count; end if;
      if abs(probability_sum - 10.0) > 0.000000001 then raise exception 'SCIENCE_CORE_V1 probabilities must sum to 10; got %', probability_sum; end if;
    end if;
    new.dataset_sha256 := ds_hash;
    new.features_sha256 := fs_hash;
    new.run_hash := internal.sha256_hex(new.model_version_id::text || '|' || new.experiment_id::text || '|' || new.run_kind || '|' || new.target_draw_number::text || '|' || new.trained_through_draw_number::text || '|' || new.git_commit_sha || '|' || new.random_seed::text || '|' || new.config::text || '|' || coalesce(ds_hash,'') || '|' || coalesce(fs_hash,'') || '|' || coalesce(pred_blob,''));
  end if;
  return new;
end;
$$;
create trigger model_run_guard before update or delete on public.model_runs for each row execute function internal.guard_model_run();

create or replace function internal.guard_ticket_change()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare pid uuid; frozen timestamptz;
begin
  if tg_table_name = 'tickets' then
    pid := case when tg_op = 'DELETE' then old.portfolio_id else new.portfolio_id end;
  else
    select t.portfolio_id into pid from public.tickets t where t.id = case when tg_op = 'DELETE' then old.ticket_id else new.ticket_id end;
  end if;
  select p.frozen_at into frozen from public.portfolios p where p.id = pid;
  if frozen is not null then raise exception 'portfolio % is frozen; tickets are immutable', pid; end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;
create trigger tickets_frozen_guard before insert or update or delete on public.tickets for each row execute function internal.guard_ticket_change();
create trigger ticket_numbers_frozen_guard before insert or update or delete on public.ticket_numbers for each row execute function internal.guard_ticket_change();

create or replace function internal.guard_portfolio()
returns trigger language plpgsql security invoker set search_path = '' as $$
declare run_frozen timestamptz; ticket_count integer; bad_ticket_count integer; total_cost numeric; ticket_blob text;
begin
  if tg_op = 'DELETE' then
    if old.frozen_at is not null then raise exception 'frozen portfolio % cannot be deleted', old.id; end if;
    return old;
  end if;
  if old.frozen_at is not null then raise exception 'frozen portfolio % cannot be modified', old.id; end if;
  if old.frozen_at is null and new.frozen_at is not null then
    select r.frozen_at into run_frozen from public.model_runs r where r.id = new.run_id;
    if run_frozen is null then raise exception 'portfolio requires a frozen model run'; end if;
    select count(*), coalesce(sum(t.cost_ars),0), count(*) filter (where coalesce(n.number_count,0) <> 5), string_agg(t.ticket_index::text || ':' || coalesce(n.numbers_text,''), '|' order by t.ticket_index)
      into ticket_count, total_cost, bad_ticket_count, ticket_blob
    from public.tickets t
    left join lateral (
      select count(*) as number_count, string_agg(tn.number::text, ',' order by tn.position) as numbers_text
      from public.ticket_numbers tn where tn.ticket_id = t.id
    ) n on true
    where t.portfolio_id = new.id;
    if ticket_count < 1 or bad_ticket_count > 0 then raise exception 'portfolio % requires at least one ticket and exactly 5 numbers per ticket', new.id; end if;
    if total_cost <> new.budget_ars then raise exception 'portfolio % budget % must equal committed ticket cost %', new.id, new.budget_ars, total_cost; end if;
    if exists (select 1 from public.tickets t where t.portfolio_id = new.id and t.cost_ars <> new.ticket_price_ars) then raise exception 'all tickets must use portfolio ticket_price_ars'; end if;
    new.portfolio_sha256 := internal.sha256_hex(new.run_id::text || '|' || new.strategy || '|' || new.ticket_price_ars::text || '|' || new.budget_ars::text || '|' || new.optimizer_seed::text || '|' || new.config::text || '|' || coalesce(ticket_blob,''));
  end if;
  return new;
end;
$$;
create trigger portfolio_guard before update or delete on public.portfolios for each row execute function internal.guard_portfolio();

create view public.science_run_integrity with (security_invoker = true) as
select
  r.id as run_id, r.experiment_id, r.model_version_id, r.run_kind, r.target_draw_number, r.trained_through_draw_number, r.frozen_at,
  count(p.number)::integer as prediction_count, count(p.probability)::integer as probability_count, sum(p.probability) as probability_sum,
  (r.trained_through_draw_number < r.target_draw_number) as leakage_cutoff_ok,
  (r.dataset_sha256 is not null and r.features_sha256 is not null and r.run_hash is not null) as hashes_complete,
  (r.frozen_at is not null and count(p.number) = 100 and count(p.probability) = 100 and abs(coalesce(sum(p.probability),0) - 10.0) <= 0.000000001 and r.trained_through_draw_number < r.target_draw_number and r.dataset_sha256 is not null and r.features_sha256 is not null and r.run_hash is not null) as science_core_valid
from public.model_runs r
left join public.model_predictions p on p.run_id = r.id
group by r.id;

create view public.science_core_status with (security_invoker = true) as
select
  (select count(*) from public.experiments) as experiments,
  (select count(*) from public.experiments where frozen_at is not null) as frozen_experiments,
  (select count(*) from public.dataset_snapshots where frozen_at is not null) as frozen_dataset_snapshots,
  (select count(*) from public.feature_snapshots where frozen_at is not null) as frozen_feature_snapshots,
  (select count(*) from public.model_runs where frozen_at is not null) as frozen_runs,
  (select count(*) from public.science_run_integrity where frozen_at is not null and not science_core_valid) as invalid_frozen_runs,
  (select count(*) from public.portfolios where frozen_at is not null) as frozen_portfolios;

alter table public.experiments enable row level security;
alter table public.experiment_models enable row level security;
alter table public.experiment_events enable row level security;
alter table public.dataset_snapshots enable row level security;
alter table public.dataset_snapshot_draws enable row level security;
alter table public.feature_snapshots enable row level security;
alter table public.feature_snapshot_values enable row level security;

revoke all on public.experiments, public.experiment_models, public.experiment_events, public.dataset_snapshots, public.dataset_snapshot_draws, public.feature_snapshots, public.feature_snapshot_values from anon, authenticated;
grant select on public.experiments, public.experiment_models, public.experiment_events, public.dataset_snapshots, public.dataset_snapshot_draws, public.feature_snapshots, public.feature_snapshot_values to anon, authenticated;
grant all on public.experiments, public.experiment_models, public.experiment_events, public.dataset_snapshots, public.dataset_snapshot_draws, public.feature_snapshots, public.feature_snapshot_values to service_role;
grant usage, select on sequence public.experiment_events_id_seq to service_role;

create policy "public_read_experiments" on public.experiments for select to anon, authenticated using (true);
create policy "public_read_experiment_models" on public.experiment_models for select to anon, authenticated using (true);
create policy "public_read_experiment_events" on public.experiment_events for select to anon, authenticated using (true);
create policy "public_read_dataset_snapshots" on public.dataset_snapshots for select to anon, authenticated using (true);
create policy "public_read_dataset_snapshot_draws" on public.dataset_snapshot_draws for select to anon, authenticated using (true);
create policy "public_read_feature_snapshots" on public.feature_snapshots for select to anon, authenticated using (true);
create policy "public_read_feature_snapshot_values" on public.feature_snapshot_values for select to anon, authenticated using (true);

grant select on public.science_run_integrity, public.science_core_status to anon, authenticated, service_role;

revoke execute on function internal.prepare_dataset_snapshot_draw() from public, anon, authenticated;
revoke execute on function internal.guard_dataset_snapshot_draw_change() from public, anon, authenticated;
revoke execute on function internal.guard_dataset_snapshot_header() from public, anon, authenticated;
revoke execute on function internal.prepare_feature_snapshot_value() from public, anon, authenticated;
revoke execute on function internal.guard_feature_snapshot_value_change() from public, anon, authenticated;
revoke execute on function internal.guard_feature_snapshot_header() from public, anon, authenticated;
revoke execute on function internal.guard_model_version_frozen() from public, anon, authenticated;
revoke execute on function internal.guard_experiment_models_change() from public, anon, authenticated;
revoke execute on function internal.guard_experiment() from public, anon, authenticated;
revoke execute on function internal.log_experiment_transition() from public, anon, authenticated;
revoke execute on function internal.prevent_event_mutation() from public, anon, authenticated;
revoke execute on function internal.guard_model_prediction_change() from public, anon, authenticated;
revoke execute on function internal.guard_model_run() from public, anon, authenticated;
revoke execute on function internal.guard_ticket_change() from public, anon, authenticated;
revoke execute on function internal.guard_portfolio() from public, anon, authenticated;

grant execute on function internal.prepare_dataset_snapshot_draw(), internal.guard_dataset_snapshot_draw_change(), internal.guard_dataset_snapshot_header(), internal.prepare_feature_snapshot_value(), internal.guard_feature_snapshot_value_change(), internal.guard_feature_snapshot_header(), internal.guard_model_version_frozen(), internal.guard_experiment_models_change(), internal.guard_experiment(), internal.log_experiment_transition(), internal.prevent_event_mutation(), internal.guard_model_prediction_change(), internal.guard_model_run(), internal.guard_ticket_change(), internal.guard_portfolio() to service_role;
