-- POCEADA LAB Python Compute Plane V1
-- App -> Supabase durable queue -> Python worker -> Supabase metrics/results.

alter table public.simulation_experiments drop constraint if exists simulation_experiments_category_check;
alter table public.simulation_experiments add constraint simulation_experiments_category_check check (category = any(array['PORTFOLIO_GEOMETRY','NULL_HISTORY','SELECTION_SHADOW','MULTIPLE_TESTING','BANKROLL','RANDOMNESS','OPTIMIZATION','CUSTOM']));
alter table public.simulation_presets drop constraint if exists simulation_presets_category_check;
alter table public.simulation_presets add constraint simulation_presets_category_check check (category = any(array['PORTFOLIO_GEOMETRY','NULL_HISTORY','SELECTION_SHADOW','MULTIPLE_TESTING','BANKROLL','RANDOMNESS','OPTIMIZATION','CUSTOM']));

create table public.simulation_jobs (
  id uuid primary key default gen_random_uuid(),
  simulation_experiment_id uuid not null references public.simulation_experiments(id) on delete cascade,
  parent_job_id uuid references public.simulation_jobs(id) on delete set null,
  preset_slug text references public.simulation_presets(slug) on delete set null,
  status text not null default 'QUEUED' check (status in ('QUEUED','CLAIMED','RUNNING','CANCELLING','CANCELLED','COMPLETED','FAILED','STALE')),
  priority smallint not null default 50 check (priority between 0 and 100),
  requested_iterations bigint not null check (requested_iterations > 0 and requested_iterations <= 1000000000),
  progress_iterations bigint not null default 0 check (progress_iterations >= 0),
  seed_base bigint not null,
  config jsonb not null default '{}'::jsonb check (jsonb_typeof(config)='object'),
  current_phase text,
  worker_id text,
  attempt integer not null default 1 check (attempt between 1 and 20),
  max_attempts integer not null default 3 check (max_attempts between 1 and 20),
  cancel_requested boolean not null default false,
  heartbeat_at timestamptz,
  lease_expires_at timestamptz,
  runtime_ms bigint check (runtime_ms is null or runtime_ms >= 0),
  result_summary jsonb not null default '{}'::jsonb check (jsonb_typeof(result_summary)='object'),
  result_sha256 text check (result_sha256 is null or result_sha256 ~ '^[0-9a-f]{64}$'),
  error_code text,
  error_message text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  check (progress_iterations <= requested_iterations)
);

create table public.simulation_workers (
  id text primary key,
  display_name text not null,
  worker_version text not null,
  engine_version text not null,
  status text not null default 'ONLINE' check (status in ('ONLINE','BUSY','DRAINING','OFFLINE')),
  capabilities jsonb not null default '{}'::jsonb check (jsonb_typeof(capabilities)='object'),
  cpu_count integer check (cpu_count is null or cpu_count > 0),
  memory_mb integer check (memory_mb is null or memory_mb > 0),
  current_job_id uuid references public.simulation_jobs(id) on delete set null,
  last_seen_at timestamptz not null default now(),
  started_at timestamptz not null default now(),
  completed_jobs integer not null default 0 check (completed_jobs >= 0),
  failed_jobs integer not null default 0 check (failed_jobs >= 0)
);

create table public.simulation_job_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null references public.simulation_jobs(id) on delete cascade,
  event_type text not null,
  message text,
  data jsonb not null default '{}'::jsonb check (jsonb_typeof(data)='object'),
  created_at timestamptz not null default now()
);

create index simulation_jobs_queue_idx on public.simulation_jobs(status, priority desc, created_at) where status='QUEUED';
create index simulation_jobs_experiment_idx on public.simulation_jobs(simulation_experiment_id, created_at desc);
create index simulation_jobs_worker_idx on public.simulation_jobs(worker_id, status) where worker_id is not null;
create index simulation_jobs_lease_idx on public.simulation_jobs(lease_expires_at) where status in ('CLAIMED','RUNNING','CANCELLING');
create index simulation_jobs_parent_idx on public.simulation_jobs(parent_job_id) where parent_job_id is not null;
create index simulation_workers_job_idx on public.simulation_workers(current_job_id) where current_job_id is not null;
create index simulation_job_events_job_idx on public.simulation_job_events(job_id, created_at desc);

alter table public.simulation_jobs enable row level security;
alter table public.simulation_workers enable row level security;
alter table public.simulation_job_events enable row level security;
grant select on public.simulation_jobs,public.simulation_workers,public.simulation_job_events to anon,authenticated;
grant all on public.simulation_jobs,public.simulation_workers,public.simulation_job_events to service_role;
grant usage,select on sequence public.simulation_job_events_id_seq to service_role;
create policy "public read simulation jobs" on public.simulation_jobs for select to anon,authenticated using (true);
create policy "public read simulation workers" on public.simulation_workers for select to anon,authenticated using (true);
create policy "public read simulation job events" on public.simulation_job_events for select to anon,authenticated using (true);

create or replace function public.create_simulation_job(p_name text,p_preset_slug text,p_requested_iterations bigint,p_seed_base bigint,p_config jsonb,p_git_commit_sha text,p_priority integer default 50)
returns public.simulation_jobs language plpgsql security invoker set search_path='' as $$
declare v_preset public.simulation_presets%rowtype; v_experiment_id uuid; v_job public.simulation_jobs%rowtype; v_slug text;
begin
  if p_requested_iterations is null or p_requested_iterations < 1 or p_requested_iterations > 1000000000 then raise exception 'requested_iterations must be between 1 and 1,000,000,000'; end if;
  if p_git_commit_sha is null or p_git_commit_sha !~ '^[0-9a-f]{40}([0-9a-f]{24})?$' then raise exception 'valid git commit sha is required'; end if;
  select * into v_preset from public.simulation_presets where slug=p_preset_slug and active=true;
  if not found then raise exception 'unknown or inactive preset %',p_preset_slug; end if;
  v_slug:='app-'||to_char(clock_timestamp(),'YYYYMMDDHH24MISSMS')||'-'||substr(gen_random_uuid()::text,1,8);
  insert into public.simulation_experiments(slug,name,preset_slug,category,hypothesis,engine_version,git_commit_sha,config,requested_iterations,seed_base,shard_count,status)
  values(v_slug,coalesce(nullif(trim(p_name),''),v_preset.name),v_preset.slug,v_preset.category,'App-launched simulation; interpretation follows the frozen preset and configuration.',v_preset.engine_version,p_git_commit_sha,coalesce(v_preset.default_config,'{}'::jsonb)||coalesce(p_config,'{}'::jsonb),p_requested_iterations,p_seed_base,1,'DRAFT') returning id into v_experiment_id;
  update public.simulation_experiments set status='FROZEN',frozen_at=now() where id=v_experiment_id;
  insert into public.simulation_jobs(simulation_experiment_id,preset_slug,status,priority,requested_iterations,seed_base,config)
  values(v_experiment_id,v_preset.slug,'QUEUED',greatest(0,least(100,coalesce(p_priority,50))),p_requested_iterations,p_seed_base,coalesce(v_preset.default_config,'{}'::jsonb)||coalesce(p_config,'{}'::jsonb)) returning * into v_job;
  update public.simulation_experiments set status='QUEUED' where id=v_experiment_id;
  insert into public.simulation_job_events(job_id,event_type,message,data) values(v_job.id,'QUEUED','Simulation queued from app',jsonb_build_object('preset',v_preset.slug,'iterations',p_requested_iterations,'seed',p_seed_base));
  return v_job;
end $$;

create or replace function public.claim_simulation_job(p_worker_id text,p_lease_seconds integer default 120)
returns setof public.simulation_jobs language plpgsql security invoker set search_path='' as $$
declare v_job public.simulation_jobs%rowtype;
begin
  with next_job as (select id from public.simulation_jobs where status='QUEUED' and cancel_requested=false order by priority desc,created_at asc for update skip locked limit 1)
  update public.simulation_jobs j set status='CLAIMED',worker_id=p_worker_id,started_at=coalesce(j.started_at,now()),heartbeat_at=now(),lease_expires_at=now()+make_interval(secs=>greatest(30,least(900,p_lease_seconds))),current_phase='claim',updated_at=now() from next_job n where j.id=n.id returning j.* into v_job;
  if v_job.id is null then return; end if;
  update public.simulation_experiments set status='RUNNING' where id=v_job.simulation_experiment_id;
  update public.simulation_workers set status='BUSY',current_job_id=v_job.id,last_seen_at=now() where id=p_worker_id;
  insert into public.simulation_job_events(job_id,event_type,message,data) values(v_job.id,'CLAIMED','Job claimed by worker',jsonb_build_object('worker_id',p_worker_id));
  return next v_job;
end $$;

create or replace function public.heartbeat_simulation_job(p_job_id uuid,p_worker_id text,p_progress_iterations bigint,p_phase text,p_lease_seconds integer default 120,p_partial_summary jsonb default '{}'::jsonb)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare v_job public.simulation_jobs%rowtype;
begin
  update public.simulation_jobs j set progress_iterations=least(j.requested_iterations,greatest(j.progress_iterations,coalesce(p_progress_iterations,j.progress_iterations))),current_phase=coalesce(p_phase,j.current_phase),status=case when j.cancel_requested then 'CANCELLING' else 'RUNNING' end,heartbeat_at=now(),lease_expires_at=now()+make_interval(secs=>greatest(30,least(900,p_lease_seconds))),result_summary=j.result_summary||coalesce(p_partial_summary,'{}'::jsonb),updated_at=now()
  where j.id=p_job_id and j.worker_id=p_worker_id and j.status in ('CLAIMED','RUNNING','CANCELLING') returning j.* into v_job;
  if v_job.id is null then raise exception 'job not owned by worker or not running'; end if;
  update public.simulation_workers set status='BUSY',current_job_id=p_job_id,last_seen_at=now() where id=p_worker_id;
  return jsonb_build_object('job_id',v_job.id,'status',v_job.status,'cancel_requested',v_job.cancel_requested,'progress_iterations',v_job.progress_iterations,'requested_iterations',v_job.requested_iterations);
end $$;

create or replace function public.complete_simulation_job(p_job_id uuid,p_worker_id text,p_result_sha256 text,p_result_summary jsonb default '{}'::jsonb,p_runtime_ms bigint default null)
returns public.simulation_jobs language plpgsql security invoker set search_path='' as $$
declare v_job public.simulation_jobs%rowtype;
begin
  if p_result_sha256 !~ '^[0-9a-f]{64}$' then raise exception 'invalid result sha256'; end if;
  update public.simulation_jobs j set status='COMPLETED',progress_iterations=j.requested_iterations,current_phase='complete',result_sha256=p_result_sha256,result_summary=j.result_summary||coalesce(p_result_summary,'{}'::jsonb),runtime_ms=coalesce(p_runtime_ms,j.runtime_ms),completed_at=now(),heartbeat_at=now(),lease_expires_at=null,updated_at=now()
  where j.id=p_job_id and j.worker_id=p_worker_id and j.status in ('CLAIMED','RUNNING','CANCELLING') and not j.cancel_requested returning j.* into v_job;
  if v_job.id is null then raise exception 'job cannot be completed'; end if;
  update public.simulation_experiments set status='COMPLETED',completed_at=now() where id=v_job.simulation_experiment_id;
  update public.simulation_workers set status='ONLINE',current_job_id=null,last_seen_at=now(),completed_jobs=completed_jobs+1 where id=p_worker_id;
  insert into public.simulation_job_events(job_id,event_type,message,data) values(v_job.id,'COMPLETED','Simulation completed',jsonb_build_object('worker_id',p_worker_id,'result_sha256',p_result_sha256,'runtime_ms',p_runtime_ms));
  return v_job;
end $$;

create or replace function public.fail_simulation_job(p_job_id uuid,p_worker_id text,p_error_code text,p_error_message text,p_runtime_ms bigint default null)
returns public.simulation_jobs language plpgsql security invoker set search_path='' as $$
declare v_job public.simulation_jobs%rowtype;
begin
  update public.simulation_jobs j set status='FAILED',error_code=left(coalesce(p_error_code,'WORKER_ERROR'),100),error_message=left(coalesce(p_error_message,'Unknown worker error'),4000),runtime_ms=coalesce(p_runtime_ms,j.runtime_ms),completed_at=now(),heartbeat_at=now(),lease_expires_at=null,current_phase='failed',updated_at=now()
  where j.id=p_job_id and j.worker_id=p_worker_id and j.status in ('CLAIMED','RUNNING','CANCELLING') returning j.* into v_job;
  if v_job.id is null then raise exception 'job cannot be failed'; end if;
  update public.simulation_experiments set status='FAILED',completed_at=now() where id=v_job.simulation_experiment_id;
  update public.simulation_workers set status='ONLINE',current_job_id=null,last_seen_at=now(),failed_jobs=failed_jobs+1 where id=p_worker_id;
  insert into public.simulation_job_events(job_id,event_type,message,data) values(v_job.id,'FAILED','Simulation failed',jsonb_build_object('worker_id',p_worker_id,'error_code',p_error_code));
  return v_job;
end $$;

create or replace function public.request_cancel_simulation_job(p_job_id uuid)
returns public.simulation_jobs language plpgsql security invoker set search_path='' as $$
declare v_job public.simulation_jobs%rowtype;
begin
  update public.simulation_jobs j set cancel_requested=true,status=case when j.status='QUEUED' then 'CANCELLED' else 'CANCELLING' end,completed_at=case when j.status='QUEUED' then now() else j.completed_at end,current_phase=case when j.status='QUEUED' then 'cancelled' else 'cancelling' end,updated_at=now()
  where j.id=p_job_id and j.status in ('QUEUED','CLAIMED','RUNNING') returning j.* into v_job;
  if v_job.id is null then raise exception 'job cannot be cancelled'; end if;
  if v_job.status='CANCELLED' then update public.simulation_experiments set status='ABORTED',completed_at=now() where id=v_job.simulation_experiment_id; end if;
  insert into public.simulation_job_events(job_id,event_type,message) values(v_job.id,'CANCEL_REQUESTED','Cancellation requested');
  return v_job;
end $$;

create or replace function public.acknowledge_cancelled_simulation_job(p_job_id uuid,p_worker_id text,p_runtime_ms bigint default null)
returns public.simulation_jobs language plpgsql security invoker set search_path='' as $$
declare v_job public.simulation_jobs%rowtype;
begin
  update public.simulation_jobs j set status='CANCELLED',completed_at=now(),lease_expires_at=null,current_phase='cancelled',runtime_ms=coalesce(p_runtime_ms,j.runtime_ms),updated_at=now() where j.id=p_job_id and j.worker_id=p_worker_id and j.cancel_requested=true and j.status='CANCELLING' returning j.* into v_job;
  if v_job.id is null then raise exception 'job cannot acknowledge cancellation'; end if;
  update public.simulation_experiments set status='ABORTED',completed_at=now() where id=v_job.simulation_experiment_id;
  update public.simulation_workers set status='ONLINE',current_job_id=null,last_seen_at=now() where id=p_worker_id;
  insert into public.simulation_job_events(job_id,event_type,message,data) values(v_job.id,'CANCELLED','Worker stopped simulation',jsonb_build_object('worker_id',p_worker_id));
  return v_job;
end $$;

create or replace function public.retry_simulation_job(p_job_id uuid)
returns public.simulation_jobs language plpgsql security invoker set search_path='' as $$
declare v_old public.simulation_jobs%rowtype; v_new public.simulation_jobs%rowtype;
begin
  select * into v_old from public.simulation_jobs where id=p_job_id for update;
  if not found or v_old.status not in ('FAILED','CANCELLED','STALE') then raise exception 'only failed/cancelled/stale jobs can be retried'; end if;
  if v_old.attempt>=v_old.max_attempts then raise exception 'max attempts reached'; end if;
  insert into public.simulation_jobs(simulation_experiment_id,parent_job_id,preset_slug,status,priority,requested_iterations,seed_base,config,attempt,max_attempts) values(v_old.simulation_experiment_id,v_old.id,v_old.preset_slug,'QUEUED',v_old.priority,v_old.requested_iterations,v_old.seed_base,v_old.config,v_old.attempt+1,v_old.max_attempts) returning * into v_new;
  update public.simulation_experiments set status='QUEUED',completed_at=null where id=v_old.simulation_experiment_id;
  insert into public.simulation_job_events(job_id,event_type,message,data) values(v_new.id,'RETRY_QUEUED','Retry queued',jsonb_build_object('parent_job_id',v_old.id,'attempt',v_new.attempt));
  return v_new;
end $$;

create or replace function public.mark_stale_simulation_jobs()
returns integer language plpgsql security invoker set search_path='' as $$
declare v_count integer;
begin
  with stale as (update public.simulation_jobs j set status='STALE',completed_at=now(),current_phase='stale',error_code='LEASE_EXPIRED',error_message='Worker heartbeat lease expired',updated_at=now() where j.status in ('CLAIMED','RUNNING','CANCELLING') and j.lease_expires_at<now() returning j.id)
  select count(*) into v_count from stale;
  update public.simulation_workers w set status='OFFLINE',current_job_id=null where w.current_job_id in (select id from public.simulation_jobs where status='STALE');
  return v_count;
end $$;

revoke execute on function public.create_simulation_job(text,text,bigint,bigint,jsonb,text,integer) from public,anon,authenticated;
revoke execute on function public.claim_simulation_job(text,integer) from public,anon,authenticated;
revoke execute on function public.heartbeat_simulation_job(uuid,text,bigint,text,integer,jsonb) from public,anon,authenticated;
revoke execute on function public.complete_simulation_job(uuid,text,text,jsonb,bigint) from public,anon,authenticated;
revoke execute on function public.fail_simulation_job(uuid,text,text,text,bigint) from public,anon,authenticated;
revoke execute on function public.request_cancel_simulation_job(uuid) from public,anon,authenticated;
revoke execute on function public.acknowledge_cancelled_simulation_job(uuid,text,bigint) from public,anon,authenticated;
revoke execute on function public.retry_simulation_job(uuid) from public,anon,authenticated;
revoke execute on function public.mark_stale_simulation_jobs() from public,anon,authenticated;
grant execute on function public.create_simulation_job(text,text,bigint,bigint,jsonb,text,integer) to service_role;
grant execute on function public.claim_simulation_job(text,integer) to service_role;
grant execute on function public.heartbeat_simulation_job(uuid,text,bigint,text,integer,jsonb) to service_role;
grant execute on function public.complete_simulation_job(uuid,text,text,jsonb,bigint) to service_role;
grant execute on function public.fail_simulation_job(uuid,text,text,text,bigint) to service_role;
grant execute on function public.request_cancel_simulation_job(uuid) to service_role;
grant execute on function public.acknowledge_cancelled_simulation_job(uuid,text,bigint) to service_role;
grant execute on function public.retry_simulation_job(uuid) to service_role;
grant execute on function public.mark_stale_simulation_jobs() to service_role;

create view public.simulation_compute_status with (security_invoker=true) as
select
 (select count(*) from public.simulation_jobs where status='QUEUED') queued_jobs,
 (select count(*) from public.simulation_jobs where status in ('CLAIMED','RUNNING','CANCELLING')) active_jobs,
 (select count(*) from public.simulation_jobs where status='COMPLETED') completed_jobs,
 (select count(*) from public.simulation_jobs where status='FAILED') failed_jobs,
 (select coalesce(sum(progress_iterations),0) from public.simulation_jobs where status in ('CLAIMED','RUNNING','CANCELLING')) processed_iterations,
 (select count(*) from public.simulation_workers where status in ('ONLINE','BUSY') and last_seen_at>now()-interval '5 minutes') online_workers,
 (select count(*) from public.simulation_workers where status='BUSY' and last_seen_at>now()-interval '5 minutes') busy_workers,
 (select coalesce(sum(progress_iterations),0) from public.simulation_jobs where status in ('CLAIMED','RUNNING','CANCELLING')) active_progress_iterations;
grant select on public.simulation_compute_status to anon,authenticated,service_role;

insert into public.simulation_presets(slug,name,category,description,engine_version,default_iterations,max_recommended_iterations,default_config,active)
values('portfolio-optimizer-v1','Portfolio Optimizer','OPTIMIZATION','Busca geometrías de tickets con baja duplicación de subconjuntos y evalúa su cobertura antes de aceptarlas como candidatas.','SIM_ENGINE_V2',250000,5000000,'{"pool_size":15,"ticket_count":6,"ticket_size":5,"objective":"unique_4_subsets","search":"deterministic_local_search"}'::jsonb,true)
on conflict(slug) do update set name=excluded.name,category=excluded.category,description=excluded.description,engine_version=excluded.engine_version,default_iterations=excluded.default_iterations,max_recommended_iterations=excluded.max_recommended_iterations,default_config=excluded.default_config,active=true;

do $$ begin
 if exists(select 1 from pg_publication where pubname='supabase_realtime') and not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='simulation_jobs') then alter publication supabase_realtime add table public.simulation_jobs; end if;
 if exists(select 1 from pg_publication where pubname='supabase_realtime') and not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='simulation_workers') then alter publication supabase_realtime add table public.simulation_workers; end if;
end $$;
